project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from quiz import views

urlpatterns = [
    path('', views.start_quiz, name='home'),  # Point to start_quiz view
    path('admin/', admin.site.urls),
    path('quiz/', include('quiz.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

quiz/urls.py
from django.urls import path

from . import views

app_name = "quiz"
urlpatterns = [
    # home page for the quiz
    path("", views.start_quiz, name="start_quiz"),
    # signup page
    path('signup/', views.signup, name='signup'),
    # quiz detail page
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    # quiz results page
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    # vote page
    path("<int:question_id>/vote/", views.vote, name="vote"),
    # flush page
    path("flush/", views.flush, name="flush"),
    # path("random/", views.random, name="random")
]

quiz/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

#model for the quiz questions
class Question(models.Model):
    def __str__(self):
        return self.question_text

    #method to check if the question was published recently
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1)<= self.pub_date <= now

    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

#model for the choices
class Choice(models.Model):

    def __str__(self):
        return self.choice_text
    #foreign key to the question model
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    #field to store the number of votes
    votes = models.IntegerField(default=0)
    #boolean field to check if the choice is correct
    correct = models.BooleanField(default=False)

class UserScore(models.Model):
    #foreign key to the user model
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    #field to store the score
    score = models.FloatField()
    #field to store the date the score was created
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username}: {self.score}"

quiz/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text="Required. Inform a valid email address.")

    class Meta:
        # User model
        model = User
        # Fields to be displayed on the form
        fields = ["username", "email", "password1", "password2"]

quiz/views.py
from typing import Any
from django.db.models import F
from django.db.models.query import QuerySet
from django.shortcuts import get_object_or_404, render, redirect
from django.http import  HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from random import choice
from django.contrib.auth.decorators import login_required
import random

from .forms import SignUpForm
from .models import Choice, Question, UserScore

class IndexView(generic.ListView):
    # Return the latest 5 questions
    template_name = "quiz/index.html"
    context_object_name = "latest_question_list"

    # Function to get the latest 5 questions 
    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[:5]
    
class DetailView(generic.DetailView):
    # Return the question and its choices
    model = Question
    # Return the question and its choices
    template_name = "quiz/detail.html"
    # Get the question and its choices
    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    # Return the question and its choices
    model = Question
    # Return the question and its choices
    template_name = "quiz/results.html"

    # Get the question and its choices
    def get_context_date(self, **kwargs):
        # Get the question and its choices
        context = super().get_context_data(**kwargs)
        # Get the selected choice AND the correct choice
        context['correct_choice'] = self.get_object().choice_set.filter(correct=True).first()
        # Return the context
        return context

# def index(request):
#     latest_question_list = Question.objects.order_by("-pub_date")[:5]
#     context = {
#         "latest_question_list": latest_question_list,
#     }
#     return render(request, "quiz/index.html", context)

# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, "quiz/detail.html", {"question": question})

# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, "quiz/results.html", {"question": question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except(KeyError, Choice.DoesNotExist):
        return render(
            request,
            "quiz/detail.html",
            {
                "question":question,
                "error_message": "You didn't select a choice",
            }
        )
    else:
        # selected_choice.votes = F("votes") + 1
        # selected_choice.save()

        # return HttpResponseRedirect(reverse("quiz:results", args=(question.id,)))

        # selected_choice.votes += 1
        # selected_choice.save()

        # Check if the selected choice is correct
        # is_correct = selected_choice.correct

        selected_choice.votes += 1
        selected_choice.save()

        #make sure the selected choice is correct
        is_correct = selected_choice.correct


        # Save the attempted question and correctness check result in the session
        if 'attempted_questions' not in request.session:
            request.session['attempted_questions'] = []

        # Save the correct answers in the session

        if 'correct_answers' not in request.session:
            request.session['correct_answers'] = 0

        # Save the attempted question and correctness check result in the session
        
        request.session['attempted_questions'].append(question_id)
        if is_correct:
            request.session['correct_answers'] += 1
        request.session.modified = True

        # Pass the correctness check result to the template
        return render(request, 'quiz/results.html', {
            'question': question,
            'selected_choice': selected_choice,
            'is_correct': is_correct,
        })

def signup(request):
    #add the signup form
    if request.method == "POST":
        form = SignUpForm(request.POST)
        #check if the form is valid
        if form.is_valid():
            form.save()
            #redirect to the login page
            return redirect("login")
    else:
        #display the form
        form = SignUpForm()
    #return the form
    return render(request, "registration/signup.html", {"form": form})

def flush(request):
    # Clear the session
    request.session.flush()
    # Redirect to the start_quiz view
    return redirect('quiz:start_quiz')

@login_required
def start_quiz(request):
    # Debug: clear session for debugging purposes

    if 'attempted_questions' not in request.session:
        request.session['attempted_questions'] = []
    if 'correct_answers' not in request.session:
        request.session['correct_answers'] = 0

    #get all unattempted questions
    attempted_questions = request.session['attempted_questions']
    all_questions = list(Question.objects.values_list('id', flat=True))

    print(f"Attempted Questions: {attempted_questions}")
    print(f"All Questions: {all_questions}")

    # Check if all questions have been attempted    

    if len(attempted_questions) >= len(all_questions):
        correct_answers = request.session['correct_answers']
        total_questions = len(all_questions)
        percentage = (correct_answers / total_questions) * 100 if total_questions > 0 else 0

                # Save the score in the database
        UserScore.objects.create(user=request.user, score=percentage)

        # Calculate average, highest, and lowest scores
        scores = UserScore.objects.filter(user=request.user).values_list('score', flat=True)
        # calculate the highest, lowest, and average scores
        highest_score = max(scores) if scores else 0
        lowest_score = min(scores) if scores else 0
        average_score = sum(scores) / len(scores) if scores else 0

        #return the completion page with the scores
        return render(request, 'quiz/completion.html',{
            'correct_answers': correct_answers,
            'total_questions': total_questions,
            'percentage': percentage,
            'highest_score': highest_score,
            'lowest_score': lowest_score,
            'average_score': average_score,
        })

    # Get the next question
    unattempted_questions = list(set(all_questions) - set(attempted_questions))
    next_question_id = choice(unattempted_questions)
    
    # Redirect to the next question frontend page
    return redirect('quiz:detail', pk=next_question_id)

@login_required
def random(request):
    questions = Question.objects.all()
    if questions:
        random_question = choice(questions)
        return HttpResponseRedirect(reverse("quiz:detail", args=(random_question.id,) ))    
    else:
        return render(request, "quiz.no_question.html", {'error': "No questions available."})
    

quiz/templates/quiz/completion.html
{% extends "nav.html" %} {% block content %}
<div class="main">
  <h1>Quiz Completed</h1>
  <p>
    You answered {{ correct_answers }} out of {{ total_questions }} questions
    correctly.
  </p>
  <p>Your score is {{ percentage }}%.</p>
  <p>Your highest score is: {{ highest_score }}%</p>
  <p>Your lowest score is: {{ lowest_score }}%</p>
  <p>Your average score is: {{ average_score }}%</p>
  <a href="{% url 'quiz:flush' %}" class="btn btn-primary">Restart Quiz</a>
</div>
{% endblock %}

quiz/templates/quiz/detail.html
{% extends "nav.html" %} {% load static %}
<link rel="stylesheet" href="{% static 'quiz/vote.css'%}" />
{% block content %}

<body>
  <form
    action="{% url 'quiz:vote' question.id %}"
    method="post"
    class="form-check"
  >
    {% csrf_token %}
    <fieldset class="detail_main">
      <legend><h1>{{ question.question_text }}</h1></legend>
      {% if error_message %}
      <p><strong>{{ error_message }}</strong></p>
      <br />
      {% endif %} {% for choice in question.choice_set.all %}
      <div>
        <input
          type="radio"
          name="choice"
          id="choice{{ forloop.counter }}"
          value="{{ choice.id }}"
          class="form-check-input"
        />
        <label
          class="form-check-label btn btn-outline-primary"
          for="choice{{ forloop.counter }}"
          >{{ choice.choice_text }}</label
        >
      </div>
      <br />
      {% endfor %}
    </fieldset>
    <div class="detail_foot">
      <input
        class="btn btn-primary"
        type="submit"
        value="Vote"
        class="submit"
      />
      <a href="{% url 'home' %}">Next Question</a>
    </div>
  </form>
</body>
{% endblock %}

quiz/templates/quiz/index.html
{% if latest_question_list %}
<ul>
  {% for question in latest_question_list %}
  <li>
    <a href="{% url 'quiz:detail' question.id %}">{{question.question_text}}</a>
  </li>
  {% endfor %}
</ul>
<a href="{% url 'quiz:random' %}">Random Quiz</a>
{% else %}
<p>No quiz are available.</p>
{% endif %}

quiz/templates/quiz/no_questions.html
<p>no questions</p>

quiz/templates/quiz/random.html
{% load static %}
<link rel="stylesheet" href="{% static 'quiz/vote.css'%}" />
<h1>HEY</h1>
{% if error %}
    <p> {{error}}</p>
{%else%}
    <h1> {{question.text}}</h1>
    <p>Published on: {{pub_date}}</p>
{%endif%}

quiz/templates/quiz/results.html
{% extends "nav.html" %} {% block content %}
<style>
  .main {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
  }
  li {
    list-style: none;
  }
</style>
<div class="main">
  <h1>{{ question.question_text }}</h1>

  <ul class="choice_list list-group">
    {% for choice in question.choice_set.all %}
    <li class="list-group-item">
      {{ choice.choice_text }} -- {{ choice.votes }}
      {% if choice == selected_choice %}
        {% if is_correct %}
          <span style="color: green;">(Correct)</span>
        {% else %}
          <span style="color: red;">(Incorrect)</span>
        {% endif %}
      {% endif %}
    </li>
    {% endfor %}
  </ul>

  <div>
    <a href="{% url 'home' %}">Next Question</a>
  </div>
</div>
{% endblock %}